### ISSUE TITLE
Compile failure / inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [ciez/regex-do#1]
The .cabal file declares `regex-do` to be compatible with `base < 5`, however, GHC disagrees, e.g. with base-4.7:

```
Configuring component lib from regex-do-3.1
Preprocessing library regex-do-3.1...
[ 1 of 21] Compiling Text.Regex.Do.Type.Internal ( src/Text/Regex/Do/Type/Internal.hs, /tmp/matrix-worker/1481362326/dist-newstyle/build/x86_64-linux/ghc-7.8.4/regex-do-3.1/build/Text/Regex/Do/Type/Internal.o )

src/Text/Regex/Do/Type/Internal.hs:21:10:
    Not in scope: type constructor or class ‘Applicative’
```

**Comment by ciez** [comment]
true: cabal bounds are inaccurate: too open. I did not want to execlude working libs

I will update base to > 4.7

what is the best process to set correct bounds? is there a lib which does this?

**Comment by hvr** [comment]
Note that you can use e.g.

https://hackage.haskell.org/package/regex-do-3.1/regex-do.cabal/edit

to fixup the meta-data w/o requiring a full new release.

As to the "best" process, we haven't one yet... unfortunately (but I'm working, slowly, on improving the situation/tooling to help with that)

However, there's the `cabal gen-bounds` command which can be used to help infer an initial set of version bounds, see  [Cabal User Guide | Generating dependency version bounds](http://cabal.readthedocs.io/en/latest/developing-packages.html#generating-dependency-version-bounds) for more details.

Also, there's https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs which helps you detect common issues (especially with the bounds of `base`) early during development.

**Comment by ciez** [comment]
I updated base in .cabal file on hackage and also here.

Thank you for suggestions.

I will also amend constraints  as soon as I become aware about incompatible libs.

**Comment by ciez** [comment]
ran cabal gen-bounds and updated .cabal to suggested bounds.
